### ISSUE TITLE
Typo in example code

### ISSUE THREAD

**Issue by GavinRay97** [cabal-club/cabal-headless#1]
`onPeerDisconnected` is just missing a `c` in the example in readme:
```js
headless.onPeerDisonnected(function (peer) {
         ^
TypeError: headless.onPeerDisonnected is not a function

```

**Comment by cblgh** [comment]
@GavinRay97 thank you! fixed it now https://github.com/cabal-club/cabal-headless/commit/6e71e8c95338a894a8042b448746a9a7e52ed88c
